import "./globals.css";
import Header from "@/components/header/Header";
// import Footer from "@/components/footer/Footer";
import { ThemeProvider } from "@/components/theme-provider";
import MyContext  from "@/helper/Context";

export const metadata = {
  title: "Shadcn UI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <MyContext>
            <Header />
            {children}
            {/* <Footer /> */}
          </MyContext>
        </ThemeProvider>
      </body>
    </html>
  );
}
