export const metadata = {
  title: "Shadcn UI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      {children}
      <h1>Feature Products</h1>
    </>
  );
}
