import { Button } from "@/components/ui/button";
import Link from "next/link";

export const metadata = {
  title: "F1",
  description: "Generated by create next app",
};
const F1 = () => {
  return (
    <>
      <h2>F1 page</h2>
      <br />
      <Link href={`/f1/f2`}>
        <Button variant={`outline`}>F2</Button>
      </Link>
      <Link href={`/f1/f3`}>
        <Button variant={`outline`}>F3</Button>
      </Link>
      <Link href={`/login`}>
        <Button variant={`outline`}>Login</Button>
      </Link>
    </>
  );
};

export default F1;
