import { Button } from "@/components/ui/button";
import Link from "next/link";

export const metadata = {
  title: "F2",
  description: "Generated by create next app",
};
const F2 = () => {
  return (
    <>
      <h2>F2 page</h2>
      <br />
      <Link href={`/f1`}>
        <Button variant={`outline`}>F1</Button>
      </Link>
    </>
  );
};

export default F2;
